name: grid_unlock
description: A community-based rideshare application.

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^0.5.22
  google_maps_webservice: ^0.0.16
  geolocator: ^5.2.1
  bloc: ^3.0.0
  flutter_bloc: ^3.0.0
  http: ^0.12.0
  json_serializable: ^3.2.5
  equatable: ^1.1.0
  permission_handler: ^4.2.0
  flutter_google_places: #^0.2.3
    git:
      url: https://github.com/fluttercommunity/flutter_google_places.git
      ref: master
  cloud_firestore: ^0.13.1
  firebase_core: ^0.4.3
  firebase_auth: ^0.15.4
  google_sign_in: ^4.1.1
  meta: ^1.1.7
  font_awesome_flutter: ^8.5.0
  user_repository:
    path: user_repository
  networks_repository:
    path: networks_repository
  rides_repository:
    path: rides_repository

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  extra_pedantic: ^1.1.1+3
  build_runner: ^1.7.1


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
    - assets/maps/daytime_map_style.json
    - assets/maps/nighttime_map_style.json
    - assets/images/networks_splash.png
    - assets/images/account_login.png

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
